### ISSUE TITLE
Adding support for non-RGB color spaces

### ISSUE THREAD

**Issue by kimikage** [kimikage/ColorBlendModes.jl#13]
- [x] Add tests for `Gray` (PR #16)
- [x] Add tests for blending `RGB` and `Gray` (PR #17)
- [x] Add support for `Lab` and `Luv`
  - `multiply`, `screen`, `overlay`, `hard-light`, `soft-light`
  - `hue`, `saturation`, `color`, `luminosity` (PR #19)
- [x] Add partial support for `HSV`, `HSL` and `HSI` (PR #20)
  - `hue`, `saturation`, `color`, `luminosity`
